import '../globals.css'
import type { Metadata } from 'next'
import localFont from'next/font/local'
import Footer from "@/app/components/Footer";

const eiko = localFont({
  src: [
    {
      path: './../fonts/eiko/PPEiko-Thin.woff',
      weight: '100',
      style: 'normal'
    },
  ],
  variable: '--font-eiko'
})

const favorit = localFont({
  src: [
    {
      path: './../fonts/favoritpro/FavoritPro-Light.woff',
      weight: '300',
      style: 'normal'
    },
  ],
  variable: '--font-favorit'
})

export const metadata: Metadata = {
  title: 'Alex Luowan',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${eiko.variable} ${favorit.variable} text-black`}>{children}<Footer></Footer></body>

    </html>
  )
}
